### ISSUE TITLE
Binance Abstraction Issue

### ISSUE THREAD

**Issue by akaniklaus** [peerchemist/cryptotik#14]
Thank you very much for Binance implementation! I am getting following error when I try to use it:
"TypeError: Can't instantiate abstract class Binance with abstract methods get_nonce"

**Comment by petko-happening** [comment]
Hi, can you tell me how did this happen? Which method were you trying to call, with which arguments?

**Comment by akaniklaus** [comment]
As far as I remember now, I just tried something like below and the first line gave that TypeError. P.S. I didn't install your library with pip, just added your folder into same directory and then imported it.

bnb = Binance(yourkey, yoursecret)
bnb.get_balances()

**Comment by petko-happening** [comment]
Can you pull the most recent code. That method is no longer present in Binance class. Also, did you run setup.py, as described?

**Comment by akaniklaus** [comment]
No, I haven't. Thank you. That might be the reason, I will try it again.

**Comment by petko-happening** [comment]
It turns out it was my mistake. get_nonce is one of the abstract methods and has to be implemented. Sorry

**Comment by akaniklaus** [comment]
@i-petko One issue about the library is the fact that as far as I have inspected from the code, the responses are not normalized, which means that we would still need to handle exchange responses differently even when using your library, so it is not as useful as it could be in our use-case. Hence, it would be perfect if you could normalize responses (such as column names) as much as possible at least for the three major supported exchanges (Poloniex, Bittrex and Binance). That would be great.

**Comment by petko-happening** [comment]
Yes, we have talked about it. Normalization should be done after all the exchanges are implemented. And that should be soon.
