### ISSUE TITLE
get_market_depth for pairs that don't exist

### ISSUE THREAD

**Issue by mh001** [peerchemist/cryptotik#3]
```
>>> Poloniex.get_market_depth("btc-usd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/cryptotik/poloniex.py", line 179, in get_market_depth
    asks = sum([Decimal(i[1]) for i in order_book["asks"]])
KeyError: 'asks'

```
This error message is because btc-usd doesn't exist (usdt-btc should be used).  The error should be handled better. What should be printed is something like "pair doesn't exist"

**Comment by peerchemist** [comment]
Every class (like Poloniex) has .get_market_pairs() method so you can see supported pairs. I still did not think of the best way to integrate this.
