### ISSUE TITLE
get_market_depth result bug

### ISSUE THREAD

**Issue by mh001** [peerchemist/cryptotik#4]
```
>>> Poloniex.get_market_depth("usdt-btc")
{'bids': Decimal('1305402.021491549563469446713'), 'asks': Decimal('738.6224445900000004128204662')}

```
The result should not have `Decimal(`

**Comment by peerchemist** [comment]
`The result should not have Decimal()`

It should, that is the python type (Decimal) used for numbers. Application using this library should convert it to any form necessary (int, float). Decimal is best type to use here to ensure precision.
